### ISSUE TITLE
Add Relic Flavour Text

### ISSUE THREAD

**Issue by jamesrudolph** [AsyncTI4/TI4_map_generator_bot#1040]
Relics are missing their Flavour Text:
https://github.com/TerTerro/TI4_map_generator_bot/blob/858c2f950bee8313b04ab909454edce5b7196d5a/src/main/resources/data/relics/pok.json
https://github.com/TerTerro/TI4_map_generator_bot/blob/5c2f2e87517221d49dbc13319e2f52e0b207afbe/src/main/resources/data/relics/codexii.json
https://github.com/TerTerro/TI4_map_generator_bot/blob/5c2f2e87517221d49dbc13319e2f52e0b207afbe/src/main/resources/data/relics/ds.json

Copy how Absol's has it:
https://github.com/TerTerro/TI4_map_generator_bot/blob/a40e3f5c6680032610f2c342fe3831eac81333c1/src/main/resources/data/relics/absol.json

**Comment by ninevra** [comment]
i'mma try this one.
