### ISSUE TITLE
Franken functionality - WIP

### ISSUE THREAD

**Issue by HolyTispoon** [AsyncTI4/TI4_map_generator_bot#114]
to make things easier for Franken on a minimal level of effort:
- allow to remove and add any leader (or else give an option to add generic leaders)
- allow to change the faction icon and put up any emoji
- allow to rename faction
- allow to 'attach' any PN from the list of all PNs

**Comment by tedw4rd** [comment]
Closing this since the basic franken tech is in, and I've added a bunch of new, more specific issues.
