### ISSUE TITLE
Move the player.getCardsInfoThread out of the queue

### ISSUE THREAD

**Issue by jamesrudolph** [AsyncTI4/TI4_map_generator_bot#1537]
https://github.com/AsyncTI4/TI4_map_generator_bot/blob/6d618faf8578bd7b63340d1e6b2c3ac543297ff8/src/main/java/ti4/helpers/Helper.java#L532

Causing this issue: https://discord.com/channels/943410040369479690/1012679443615064104/1218527359037079686

**Comment by Fingon00** [comment]
Fixed this by creating a version which didnt complete, as moving it out of the queue seemed impossible

**Comment by jamesrudolph** [comment]
ah, I was just going to do a `ThreadChannel thread = player.getCardsinfoThread()` right before the queue and just pass it in
