### ISSUE TITLE
Covert legislation info text gives too much information in conditional agendas

### ISSUE THREAD

**Issue by yamac-kurtulus** [AsyncTI4/TI4_map_generator_bot#1565]
This came up in one of my games, we had covert legislation: 
_When this agenda is revealed, the speaker draws the next card in the agenda deck but does not reveal it to the other players. Instead, the speaker reads the eligible outcomes aloud (for, against, elect Elect Player, etc.). The other Players vote for these outcomes as if they were outcomes of this agenda, without knowing their effects._

Then in the action thread, we recieved this message, and we had laws in play:
"the agenda target is For/Against (When this agenda is revealed, if there are no laws in play, discard this card and reveal another agenda from the top of the deck.). Sent the agenda to the speakers cards info"

I believe the bit in parentheses gives too much information. The agenda can just be discarded when there are no laws, and continue with the next one, without compromising covert legislation.

**Comment by Fingon00** [comment]
This got fixed
