### ISSUE TITLE
Automated cleanup of fog game roles/channels

### ISSUE THREAD

**Issue by adam133** [AsyncTI4/TI4_map_generator_bot#1713]
Currently a bit of a pain for an admin to cleanup fog games. Be nice to have some more automation for them in /game end

**Comment by jamesrudolph** [comment]
What channels are there for fog games?
- GM
- Main Channel (actions)
- channel per player

**Comment by adam133** [comment]
Also the game category

**Comment by teuschb** [comment]
Wrong buttons. I love this. I'd also love if it could change the end game so that channels don't immediately become public when games end - I think what happens in fog should stay in the fog

**Comment by Fingon00** [comment]
I think this is done
