### ISSUE TITLE
TIGL Automatically handle Rank Roles

### ISSUE THREAD

**Issue by jamesrudolph** [AsyncTI4/TI4_map_generator_bot#2117]
- grab roles at game startup to determine role ranking up from
 - player field, playerTIGLRankAtGameStart
 - game field, minimumTIGLRankAtGameStart
- auto-assign new role upon winning game end
- post rank-ups to TIGL channel
- hero roles, auto remove role from old player, add to new, special message in TIGL channel

TIGLHelper for all tigly methods
- role enum
 - ID, name, roleID

**Comment by teuschb** [comment]
This one would be huge. If it would ping me and tell me whether the winner ranked up, and to what rank, that would save me a lot of time even if I still do the rest manually

**Comment by teuschb** [comment]
<google-sheets-html-origin><style type="text/css"></style>
RoleName | RoleID
-- | --
Async Rank - Minister | 1171907111110844416
Async Rank - Agent | 1171907881096970271
Async Rank - Commander | 1199486443928686592
Async Rank - Hero | 1234988242391273603

**Comment by jamesrudolph** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jimru/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jimru/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


ID | RoleName | RoleID
-- | -- | --
MINISTER | Async Rank -   Minister | 1171907111110844416
AGENT | Async Rank - Agent | 1171907881096970271
COMMANDER | Async Rank -   Commander | 1199486443928686592
HERO | Async Rank - Hero | 1234988242391273603
EMPEROR | Async Rank -   Galactic Emperor | 1287034482616176712
HERO_WINNU | Async Rank - Mathis Mathinus | 1234988559438581861
HERO_SARDAKK | Async Rank -   Sh'val, Harbinger | 1254824548096933929
HERO_JOLNAR | Async Rank - Rin, The Master's Legacy | 1283794468008493122
HERO_MAHACT | Async Rank -   Airo Shir Aur | 1254488587001663569
HERO_EMPYREAN | Async Rank - Conservator Procyon | 1277729896935723081
HERO_NAALU | Async Rank -   The Oracle | 1275461047163289630
HERO_MUAAT | Async Rank - Adjudicator Ba'al | 1272999332978626703
HERO_NOMAD | Async Rank -   Ahk-Syl Siven | 1272999680879362100
HERO_NEKRO | Async Rank - UNIT.DSGN.FLAYESH | 1285084515752087736
HERO_SOL | Async Rank -   Jace X, 4th Air Legion | 1252648922745278514
HERO_ARGENT | Async Rank - Mirik Aun Sissiri | 1282864241174642793
HERO_NAAZ | Async Rank -   Hesh and Prit | 1263960652175900838
HERO_ARBOREC | Async Rank - Letani Miasmiala | 1276264769409781911
HERO_YIN | Async Rank -   Dannel of the Tenth | 1287035313256136785
HERO_KELERESX | Async Rank - Odlynn Myrr | 1252648551943639132
HERO_KELERESM | Async Rank -   Harka Leeds | 1272999113729900554
HERO_YSSARIL | Async Rank - Kyver, Blade and Key | 1242217137850810439



</body>

</html>
