### ISSUE TITLE
Discordant Stars: The Ghemina Raiders - Ready for implementation

### ISSUE THREAD

**Issue by CptSomno** [AsyncTI4/TI4_map_generator_bot#231]
The Ghemina Raiders have two special things that make them different:
first, they have two Heroes. No big deal, that should already be implemented through the properties lists

second, they have to different flagships. Meaning, that we both need an additional attachment point for flag ships in the reinforcements (another issue) but more importantly we need a way to distinguish them. Both visually as well as command-and-bot-wise.

These are name tags in two different colour schemes (tied to the colours on the reinforcements) which are layered on top of the respective flag ships. There is no offset between the flagship graphic and the overlay graphic.

FoW: the "Lord"/"Lady" overlay for the flaggies are only displayed when a player has vision of the Ghemina player area

pa_leaders_hero_ghemina_lord_rdy.png
pa_leaders_hero_ghemina_lord_exh.png
pa_leaders_hero_ghemina_lady_rdy.png
pa_leaders_hero_ghemina_lady_exh.png

**Comment by Fingon00** [comment]
This is done
