### ISSUE TITLE
Discordant Stars: The Myko Mentori - Ready for implementation

### ISSUE THREAD

**Issue by CptSomno** [AsyncTI4/TI4_map_generator_bot#252]
The Myko Mentory have two special things we need to be able to add:
first, they roll a couple of omen dice which they can use during their round. I came up with this solution: 50*150 px tabs that go next to the leaders:

![pa_ds_myko_omen_8](https://user-images.githubusercontent.com/102144449/232147635-17105255-5a0a-4445-ac4c-43e1692197c0.png)

file names in repo:
pa_ds_myko_omen_0.png
pa_ds_myko_omen_1.png
...
pa_ds_myko_omen_9.png

an easy /add_omen [value1],[value2],...,[valuex] should be good. To keep things modular and because I like interchangeable faction logos wherever possible, put pc_attribute_[faction].png at 2,109
Draw the faction icon first, then the omen tab.

The second thing:
as soon the hero is unlocked, it "collects" every single other hero that is played. When you pop the hero, you can choose which of the collected Heroes you want to copy. I think the easiest solution would be a generic /leaders_add/remove subcommand with a dropdown of all leaders. E.g. when Sol pops jace X the Myko player hacks in /leaders_add sol hero and boom, it's displayed next to the Myko Hero. A purge all heroes command may be useful, but given its rare use cases not needed that much.

Oh, and the Commodity cap increases for every myko spacedock presently on the board. That's low prio though, as the players can change that easily via player stats.

**Comment by Fingon00** [comment]
Doneyans
