### ISSUE TITLE
Discordant Stars: The Veldyr Sovereignty (veldyr) - Ready for implementation

### ISSUE THREAD

**Issue by CptSomno** [AsyncTI4/TI4_map_generator_bot#256]
nothing fancy here. But Veldyr have 4 attachment PNs that do not count towards attachment objectives - but only for the veldyr player. So when veldyr controls a planet with a sole veldyr attachment (attachment_veldyr1/2/3/4.png), I'd like to display pc_upgrade_exh.png (greyed-out version of the upgrade pips icon in the planet tab) instead of the normal one.
![pc_upgrade_exh](https://user-images.githubusercontent.com/102144449/232160829-aeb59e50-f449-4db7-8918-2afca7f55ee8.png)

**Comment by Fingon00** [comment]
Idk maybe they changed this rule, but I think it doesnt count towards attachment objectives for anyone
