### ISSUE TITLE
Discordant Stars: The Zealots of Rhodun (zealots) - Ready for implementation

### ISSUE THREAD

**Issue by CptSomno** [AsyncTI4/TI4_map_generator_bot#261]
The Zealots of Rhodun have a hero that, when played, grants them to gain any three non-faction techs. Those techs are purged at the end of the round.
To visualize this I've come up with two sets of layers, one "online" layer and one "purged" layer:
![rhodun tech hero](https://user-images.githubusercontent.com/102144449/232341107-5f60e08d-cbb1-432e-bb12-13e60804f9a1.png)
![rhodun tech purged](https://user-images.githubusercontent.com/102144449/232341108-26486758-9f79-4bdf-88b9-803807c616ec.png)

The online layer goes by the name pa_tech_techicons_zealots_rdy/exh.png and replaces the pa_tech_techicons_biotic/propulsion/cybernetic/warfare_rdy/exh.png icon.

The purged layer goes by pa_tech_techicons_zealotspurged_rdy/exh.png and replaces the normal techicon layer just as the online layer. BUT: it has to be drawn on top of the pa_tech_techname layer.

Unit techs:
Almost same as above, two types of layer: one zealots and one zealotspurged.
Example for Dreadnought tech:
pa_tech_unitsnew_zealots_dn2.png
pa_tech_unitsnew_zealotspurged_dn2.png
![pa_tech_unitsnew_zealots_dn2](https://user-images.githubusercontent.com/102144449/232345445-d9333620-bed3-4892-9ff5-871bf231176f.png)
![pa_tech_unitsnew_zealotspurged_dn2](https://user-images.githubusercontent.com/102144449/232345447-bf393bc7-dc30-4038-91dd-0b50184ebcb6.png)

These get just painted on top of the corresponding unit upgrade tab. I did these for all unit upgrades including the Flagship. One never knows...

We need a special command to switch a tech between normal, online and purged, something like /special zealotshero (option tech)(option state normal/online/purged)

**Comment by jamesrudolph** [comment]
@Fingon00 I imagine you coded this hero, but does it use these image assets? Just trying to clean up this issue log

**Comment by Fingon00** [comment]
No dont think so. At the end of the resolution and whatnot I have a button called purgeTech_ that right now only removes the tech. It would be easy to hook that up to also track what tech got purged, and then to hook that tracker up to display the purged images, but we dont currently have that
