### ISSUE TITLE
Discordant Stars: The Li-Zho Dynasty - Ready for implementation

### ISSUE THREAD

**Issue by CptSomno** [AsyncTI4/TI4_map_generator_bot#268]
The Li-Zho come with their own set of secret hand cards: Trap cards, that get attached to planets.

I made another properties file for those cards:
[DS_handcards.properties](https://github.com/TerTerro/TI4_map_generator_bot/blob/DiscordantStars/src/main/resources/info/DS_handcards.properties)

we need commands to attach such card to a planet (face down), swap two already attached cards without revealing them and finally a command to reveal them, which returns the card to the Li-Zho player's hand.

These Trap token count as attachments towards game effects, but not for the Li-Zho player. So if a Trap token is the sole attachment on a planet controlled by Li-Zho I'd like to display the greyed-out "attachment" Icon on the planet tab, analogue to the Veldyr PNs

![pa_ds_lizh_trap_back](https://user-images.githubusercontent.com/102144449/232608317-9d4a0549-3e26-40a7-b40f-7d675abe2176.png)

This 50*150 icon goes into player area left of the reinforcements unit box.
pa_ds_lizh_trap_back.png

add the number of remaining cards in hand from the black reinforcement numbers to 6,68 px from top left corner

pa_reinforcements_numbers_[number]_blk.png

**Comment by Fingon00** [comment]
Believe this is done
