### ISSUE TITLE
Discordant Stars: Augurs of Ilyxium (augers) - Ready for implementation

### ISSUE THREAD

**Issue by CptSomno** [AsyncTI4/TI4_map_generator_bot#341]
We need a command to draw public objectives into a players hand, play it from there into the player area, a command to bury it under the respective deck and a command to show the PO in hand to another player. Maybe a fifth command to place a PO on top of the respective deck as well, for good measure.

Commander: Agenda Vote count: additional +1 vote for every 2 techs the ilyxium player owns

**Comment by Fingon00** [comment]
I believe this is done
