### ISSUE TITLE
eliminate command should not remove Mahact Imperia banners

### ISSUE THREAD

**Issue by HolyTispoon** [AsyncTI4/TI4_map_generator_bot#640]
When a player is eliminated, if Mahact (or Imperia owner in Franken) has their token in fleet, they keep the alliance. Right now the eliminate player removes them

**Comment by Fingon00** [comment]
Fixed. /eliminate now marks player as a dummy and removes their stuff (does full eliminate) but does not remove the player object from the game entirely.
