### ISSUE TITLE
/search colours

### ISSUE THREAD

**Issue by jamesrudolph** [AsyncTI4/TI4_map_generator_bot#895]
show fancy pic of the units

**Comment by HolyTispoon** [comment]
+1
Also when the bot offers you to pick colors if you scroll through all of them - just to see what's on offer - it bugs out and won't let you pick anything. You have to restart up with a slash command like in the Stone Age.

**Comment by jamesrudolph** [comment]
completed by @bradleysigma with #1972

**Comment by bradleysigma** [comment]
@HolyTispoon's subissue was also fixed by #1922.
