### ISSUE TITLE
Monuments+ Homebrew

### ISSUE THREAD

**Issue by jamesrudolph** [AsyncTI4/TI4_map_generator_bot#967]
https://discord.com/channels/743629929484386395/990063985531441162

https://cdn.discordapp.com/attachments/990063985531441162/1166179103918002296/Monuments_Rules_2.1.pdf

**Comment by jamesrudolph** [comment]
Spreadsheet: https://docs.google.com/spreadsheets/d/192Yj3gJ55dYLa0OcH6lW3OGTDWNsMwCLXLf0MW4iYrw

**Comment by Cacotopos** [comment]
I've copied and updated the above spreadsheet to include DS factions: https://docs.google.com/spreadsheets/d/1YwlHahowMALEQtFs_lLgZ1Q0OXuCdc-G9WNywQ8JtiU/edit?usp=share_link

**Comment by jamesrudolph** [comment]
Almost done, just need to make it easy to enable the mode:
- command to add/remove monuments to factions & swap SC deck (maybe should use a flag on construction play instead of it's own SC?)
- add symbol to corner of map
- add game flag
- add the missing cards/decks so/ag/ac

**Comment by Cacotopos** [comment]
Agree re strategy card - there is a 'keep this with the construction strategy' added card to avoid doing a custom SC, which might be useful: 
![Monuments Strategy Card Front](https://github.com/user-attachments/assets/1c6a99a5-9d88-457f-b51f-1b659fbdc4a2)

**Comment by Cacotopos** [comment]
Jesus that was big lol
